#!/bin/sh
set -e

# Stash unstaged changes
git stash -q --keep-index

# Convert PDF to JPG
convert -density 600 EstebanRomo_Resume.pdf -resample 300 -alpha remove EstebanRomo_Resume.jpg

# Stage updated files
git add -u

# Re-apply original unstaged changes
git stash pop -q